FROM node:20

WORKDIR /app
# COPY ./build_protos.sh /opt/build_protos.sh
COPY . .
# RUN sudo apt-get update
# RUN sudo apt-get install ghostscript
# RUN sudo apt-get install graphicsmagick

RUN yarn
RUN yarn run generate

EXPOSE 8080

CMD ["yarn", "dev"]
