FROM node:18

WORKDIR /app

COPY app-service/package.json ./
COPY app-service/prisma ./prisma/

RUN yarn

RUN yarn run generate

COPY ./app-service .

# RUN /opt/build_protos.sh

EXPOSE 8080

CMD ["yarn", "dev"]
