# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inference_service_pb2 as inference__service__pb2


class InferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChatResponse = channel.unary_stream(
            "/inferenceServiceServer.InferenceService/GetChatResponse",
            request_serializer=inference__service__pb2.ChatDetails.SerializeToString,
            response_deserializer=inference__service__pb2.TutorResponse.FromString,
        )
        self.ServerConnectionCheck = channel.unary_unary(
            "/inferenceServiceServer.InferenceService/ServerConnectionCheck",
            request_serializer=inference__service__pb2.ReturnConnectedCheck.SerializeToString,
            response_deserializer=inference__service__pb2.ConnectedCheckResponse.FromString,
        )


class InferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChatResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ServerConnectionCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetChatResponse": grpc.unary_stream_rpc_method_handler(
            servicer.GetChatResponse,
            request_deserializer=inference__service__pb2.ChatDetails.FromString,
            response_serializer=inference__service__pb2.TutorResponse.SerializeToString,
        ),
        "ServerConnectionCheck": grpc.unary_unary_rpc_method_handler(
            servicer.ServerConnectionCheck,
            request_deserializer=inference__service__pb2.ReturnConnectedCheck.FromString,
            response_serializer=inference__service__pb2.ConnectedCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "inferenceServiceServer.InferenceService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChatResponse(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/inferenceServiceServer.InferenceService/GetChatResponse",
            inference__service__pb2.ChatDetails.SerializeToString,
            inference__service__pb2.TutorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ServerConnectionCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/inferenceServiceServer.InferenceService/ServerConnectionCheck",
            inference__service__pb2.ReturnConnectedCheck.SerializeToString,
            inference__service__pb2.ConnectedCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
