# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17inference_service.proto\x12\x16inferenceServiceServer"\x1e\n\x0b\x43hatDetails\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t"%\n\rTutorResponse\x12\x14\n\x0cresponsePart\x18\x01 \x01(\t"+\n\x14ReturnConnectedCheck\x12\x13\n\x0breturnCheck\x18\x01 \x01(\x08"+\n\x16\x43onnectedCheckResponse\x12\x11\n\tconnected\x18\x01 \x01(\x08\x32\xee\x01\n\x10InferenceService\x12\x61\n\x0fGetChatResponse\x12#.inferenceServiceServer.ChatDetails\x1a%.inferenceServiceServer.TutorResponse"\x00\x30\x01\x12w\n\x15ServerConnectionCheck\x12,.inferenceServiceServer.ReturnConnectedCheck\x1a..inferenceServiceServer.ConnectedCheckResponse"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "inference_service_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _CHATDETAILS._serialized_start = 51
    _CHATDETAILS._serialized_end = 81
    _TUTORRESPONSE._serialized_start = 83
    _TUTORRESPONSE._serialized_end = 120
    _RETURNCONNECTEDCHECK._serialized_start = 122
    _RETURNCONNECTEDCHECK._serialized_end = 165
    _CONNECTEDCHECKRESPONSE._serialized_start = 167
    _CONNECTEDCHECKRESPONSE._serialized_end = 210
    _INFERENCESERVICE._serialized_start = 213
    _INFERENCESERVICE._serialized_end = 451
# @@protoc_insertion_point(module_scope)
