"""initial schema

Revision ID: 061cbbc566bb
Revises: 5377220c5f58
Create Date: 2023-02-04 10:43:52.197141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "061cbbc566bb"
down_revision = "5377220c5f58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
