"""Initial migration

Revision ID: 5377220c5f58
Revises: 
Create Date: 2022-10-12 05:44:31.254987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5377220c5f58"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "applications",
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("credit_score", sa.Integer(), nullable=True),
        sa.Column("monthly_debt", sa.Integer(), nullable=True),
        sa.Column("monthly_income", sa.Integer(), nullable=True),
        sa.Column("bankruptcies", sa.Integer(), nullable=True),
        sa.Column("delinquencies", sa.Integer(), nullable=True),
        sa.Column("vehicle_value", sa.Integer(), nullable=True),
        sa.Column("loan_amount", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "offers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("apr", sa.Float(), nullable=True),
        sa.Column("monthly_premium", sa.Integer(), nullable=True),
        sa.Column("term_length", sa.Integer(), nullable=True),
        sa.Column("accept", sa.Boolean(), nullable=True),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("offers")
    op.drop_table("applications")
    op.drop_table("users")
    # ### end Alembic commands ###
