name: Sandbox app-service CD

on:
  push:
    branches:
      - sandbox
    paths:
      - "services/app-service/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Sandbox

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # # For the migration down below
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'yarn'
      #     cache-dependency-path: services/app-service/yarn.lock

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          workload_identity_provider: "projects/617839389948/locations/global/workloadIdentityPools/github-actions/providers/gha-provider"
          service_account: "terraform@sandbox-382905.iam.gserviceaccount.com"
          access_token_lifetime: 600s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: services/
          file: services/app-service/Dockerfile
          push: true
          platform: linux/amd64
          tags: |
            us-west1-docker.pkg.dev/sandbox-382905/app-service/app-service:${{ github.sha }}
            us-west1-docker.pkg.dev/sandbox-382905/app-service/app-service:latest

      # Migrate DB
      # Removing for now because we need to whitelist GHA job runner IPs on our DB, and I don't want to do that yet
      # - name: Install Dependencies
      #   working-directory: services/app-service
      #   run: yarn
      # - name: Migrate Database
      #   working-directory: services/app-service
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}
      #   run: yarn run migrate:prod

      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          image: us-west1-docker.pkg.dev/sandbox-382905/app-service/app-service:${{ github.sha }}
          service: app-service
          region: us-west1
          platform: managed
          project: sandbox-382905
          allow-unauthenticated: true
