name: Sandbox inference-service CD

on:
  push:
    branches:
      - sandbox
    paths:
      - "services/inference_service/**"
      - "services/app-service/prisma/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: access_token
          workload_identity_provider: "projects/617839389948/locations/global/workloadIdentityPools/github-actions/providers/gha-provider"
          service_account: "terraform@sandbox-382905.iam.gserviceaccount.com"
          access_token_lifetime: 600s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-west2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: services/
          file: services/inference_service/Dockerfile
          push: true
          platform: linux/amd64
          tags: |
            us-west1-docker.pkg.dev/sandbox-382905/inference-service/inference_service:${{ github.sha }}
            us-west1-docker.pkg.dev/sandbox-382905/inference-service/inference_service:latest

      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          image: us-west1-docker.pkg.dev/sandbox-382905/inference-service/inference_service:${{ github.sha }}
          service: inference-service
          region: us-west1
          platform: managed
          project: sandbox-382905
          allow-unauthenticated: true
